version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tri-legal-web
    ports:
      - "8080:80"
    restart: unless-stopped
~                                                                                                                       ~                                   