export const inputFields = [
  {
    id: "firstName",
    name: "firstName",
    label: "First Name",
    type: "text",
    placeholder: "First Name",
    required: true,
    colSpan: "sm:col-span-1",
  },
  {
    id: "lastName",
    name: "lastName",
    label: "Last Name",
    type: "text",
    placeholder: "Last Name",
    required: true,
    colSpan: "sm:col-span-1",
  },
  {
    id: "email",
    name: "email",
    label: "Email Address",
    type: "email",
    placeholder: "Email Address",
    required: true,
    colSpan: "sm:col-span-2",
  },
  {
    id: "phone",
    name: "phone",
    label: "Phone Number",
    type: "tel",
    placeholder: "Phone Number",
    required: true,
    colSpan: "sm:col-span-2",
  },
];
